name: master-actions
on:
  push:
    branches: [master]
  pull_request:
    branches: [ master ]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: controleer repositories
        uses: actions/checkout@v2
      - name: setup the jdk
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: cache the maven supplies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}      
        
  DockerHub:
   name: img --> dockerhub
   runs-on: ubuntu-latest
   steps:
     - name: check repo
       uses: actions/checkout@v2
     - name: push naar hub
       uses: docker/build-push-action@v1
       with:
           username: ${{secrets.DOCKER_USERNAME}}
           password: ${{secrets.DOCKER_PASSWORD}}
           repository: eliasbd2000/bs2_labo6
           tags: latest
           tag_with_ref: true
           
           
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: push tag
        id: tag_version
        uses: eliasbeddegenoodts/action-automatic-releases@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: actions/create-release@v1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }} 
